### ISSUE TITLE
Preset k8s doesn't work in GHA out of the box

### ISSUE THREAD

**Issue by dimaqq** [canonical/concierge#51]
```
Run sudo concierge prepare --juju-channel=3/stable --charmcraft-channel=3.x/stable -p "k8s"
time=2025-0[4](https://github.com/canonical/operator/actions/runs/14583800660/job/40905574645#step:3:5)-22T00:12:24.910Z level=INFO msg="Preset selected" preset=k8s
time=2025-04-22T00:12:32.8[5](https://github.com/canonical/operator/actions/runs/14583800660/job/40905574645#step:3:6)1Z level=INFO msg="Installed snap" snap=charmcraft
time=2025-04-22T00:12:36.794Z level=INFO msg="Installed apt package" package=python3-pip
time=2025-04-22T00:12:37.217Z level=INFO msg="Installed apt package" package=python3-venv
time=2025-04-22T00:12:39.973Z level=INFO msg="Installed snap" snap=jq
time=2025-04-22T00:12:42.909Z level=INFO msg="Installed snap" snap=yq
time=2025-04-22T00:13:05.720Z level=INFO msg="Installed snap" snap=rockcraft
time=2025-04-22T00:13:18.513Z level=INFO msg="Installed snap" snap=k8s
time=2025-04-22T00:13:23.8[6](https://github.com/canonical/operator/actions/runs/14583800660/job/40905574645#step:3:7)5Z level=INFO msg="Installed snap" snap=kubectl
time=2025-04-22T00:13:24.395Z level=INFO msg="Refreshed snap" snap=lxd
Command: /snap/bin/k8s status
time=2025-04-22T00:13:29.430Z level=INFO msg="Prepared provider" provider=lxd
Output:
Error: The node is not part of a Kubernetes cluster. You can bootstrap a new cluster with:
  sudo k[8](https://github.com/canonical/operator/actions/runs/14583800660/job/40905574645#step:3:9)s bootstrap
Command: /snap/bin/k8s bootstrap
Output:
Bootstrapping the cluster. This may take a few seconds, please wait.
Error: Failed to bootstrap the cluster.
The error was: failed after potential retry: wait check failed: failed to POST /k8sd/cluster: failed to bootstrap new cluster: Failed to run post-bootstrap actions: pre-init checks failed for bootstrap node: The path '/run/containerd' required for the containerd socket already exists. This may mean that another service is already using that path, and it conflicts with the k8s snap. Please make sure that there is no other service installed that uses the same path, and remove the existing directory.(dev-only): You can change the default k8s containerd base path with the containerd-base-dir option in the bootstrap / join-cluster config file.
```

That error repeats on and on.

Sample GHA:

```yaml
name: ops Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '42 7 25 * *'
  # Temporary, don't merge the PR trigger
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        juju-channel: ['3/stable']
        charmcraft-channel: ['3.x/stable']
        preset: ['k8s']

    steps:
      - run: sudo snap install --classic concierge
      - run: sudo concierge prepare --juju-channel=${{ matrix.juju-channel }} --charmcraft-channel=${{ matrix.charmcraft-channel }} -p "${{ matrix.preset }}"
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx tox -e integration
```

I have also run into this when trying Concierge manually on my home machine (fresh Ubuntu 24.04 desktop install)... and I can't recall how I fixed it exactly, but I had to make some manual tweak somewhere.
