### ISSUE TITLE
feature request: teach concierge to set juju/charm architecture (by default?)

### ISSUE THREAD

**Issue by taurus-forever** [canonical/concierge#68]
Hi,

[Data team uses concierge with several architectures](https://github.com/canonical/postgresql-operator/blob/5c1976477c6ffbd6a06a6576b70a68aae5aef8ab/spread.yaml#L136-L138) for CI tests.
It requires to set juju model-constrains on spread.yaml manually:

```
# Unable to set constraint on all models because of Juju bug:
# https://bugs.launchpad.net/juju/+bug/2065050
juju set-model-constraints arch="$(dpkg --print-architecture)"
```

The same time, we have juju model configuration in concierge.yaml (but we can't call subhell there):
```
juju:
  model-defaults:
    logging-config: <root>=INFO; unit=DEBUG
  bootstrap-constraints:
    arch: "$(dpkg --print-architecture)" <<<<<<
```

It is possible to introduce some concierge label/variable for the current architecture? E.g.:
```
juju:
  model-defaults:
    logging-config: <root>=INFO; unit=DEBUG
  bootstrap-constraints:
    arch: CONCIERGE_CURRENT_ARCH
```
... or even better: teach concierge to set Juju model architecture to the current (spread backend architecture)?

Thank you!
