### ISSUE TITLE
Concierge times out setting up lxd controller along kubernetes controller

### ISSUE THREAD

**Issue by Gu1nness** [canonical/concierge#70]
I have a concierge file which is pretty simple and bootstraps + enables two controllers:

```yaml
juju:
  model-defaults:
    logging-config: <root>=INFO; unit=DEBUG
providers:
  lxd:
    enable: true
    bootstrap: true
  microk8s:
    enable: true
    bootstrap: true
    addons:
      - dns
      - hostpath-storage
      - metallb:10.64.140.43-10.64.140.49

host:
  snaps:
    jhack:
      channel: latest/edge
      connections:
        - jhack:dot-local-share-juju snapd
 ```

On Github runners, it fails regularly with a timeout on the [bootstrap of LXD controller](https://github.com/canonical/mongo-single-kernel-library/actions/runs/15777986945/job/44477000963?pr=40#step:7:2584)
It reaches the [20 minutes timeout](https://github.com/canonical/mongo-single-kernel-library/actions/runs/15777986945/job/44477000963?pr=40#step:7:2451)

I have tried inverting lxd and microk8s in the configuration, and it changes nothing.

This happens 5-10% of the time on Github CI
